title: Long Short-Term Memory Neural Network for Modeling the English language
name: LSTM NN
description: Long Short-Term Memory (LSTM) neural network for modeling the English language.
author: Luisa Rojas
theme: jekyll-theme-minimal